#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int planets_array = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int left = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030001
			public const int Addbtn = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int AddbtnCal = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int AddbtnTodo = 2130903043;
			
			// aapt resource value: 0x7F030000
			public const int AddEventbtn = 2130903040;
			
			// aapt resource value: 0x7F030005
			public const int Cancelbtn = 2130903045;
			
			// aapt resource value: 0x7F030004
			public const int CancelEventbtn = 2130903044;
			
			// aapt resource value: 0x7F030006
			public const int departmentTextView = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int desciptionEditText = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int historyCheckBox = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int listView1 = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int listViewTodo = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int nameTextView = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int next = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int nextLife = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int nextTodo = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int noteTxt = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int previous = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int previousLife = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int previousTodo = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int shareCheckBox = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int startDateSpinner = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int textView1 = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int textView2 = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int textView4 = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int titleEditText = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int titletxt = 2130903065;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int CalendarCard = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int CalendarHolderItem = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int CalendarView = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int LifeNoteCard = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int LifeNoteHolderItem = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int LifenoteView = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int Main = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int ToDoCard = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int TodoHolderItem = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int TodoView = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int planet_prompt = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
